name: Build Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Publish Launcher
      run: |
        dotnet publish PBNG-Ecosystem/Launcher -c Release -r win-x64 --self-contained true -o Build

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Build Installer
      run: |
        ISCC.exe PBNG-Ecosystem\Installer\installer.iss

    - uses: actions/upload-artifact@v4
      with:
        name: Installer
        path: PBNG-Ecosystem/Installer/Output/
