name: Build FULL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Siapkan Ikon dan Folder
        shell: pwsh
        run: |
          # 1. Buat folder assets
          New-Item -ItemType Directory -Path "assets" -Force
          
          # 2. Cari file png (yang ada kodenya itu)
          $pngFile = Get-ChildItem -Recurse -Filter "*.png" | Where-Object { $_.Name -like "*ea9de755*" } | Select-Object -First 1
          
          if ($pngFile) {
            # Copy dan rename ke assets/logo.ico (huruf kecil semua)
            Copy-Item $pngFile.FullName -Destination "assets/logo.ico" -Force
            Write-Host "Ikon sukses disiapkan di: assets/logo.ico"
          }
          
          # 3. Pastikan folder output ada
          New-Item -ItemType Directory -Path "Output" -Force

      - name: Publish Projects
        shell: pwsh
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o publish/all

      - name: Build Installer
        shell: pwsh
        run: |
          choco install innosetup -y
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer.iss"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PBNG-INSTALLER
          path: Output/*.exe
